#ifndef BLE_UUIDS_H
#define BLE_UUIDS_H

#include <zephyr/bluetooth/uuid.h>

/* 16-bit custom vendor UUIDs — the wire contract.  Documented in
 * docs/ble-protocol.md; mirrored by scripts/protocol.py and
 * scripts/ble_control.py.
 */
#define BT_UUID_CATERPILLAR_SVC_VAL     0xFFE0
#define BT_UUID_CATERPILLAR_FREQ_VAL    0xFFE1
#define BT_UUID_CATERPILLAR_VOLT_VAL    0xFFE2
#define BT_UUID_CATERPILLAR_VDCMEAS_VAL 0xFFE3
#define BT_UUID_CATERPILLAR_RAIL_VAL    0xFFE4
#define BT_UUID_CATERPILLAR_DRV_VAL     0xFFE5
#define BT_UUID_CATERPILLAR_STATUS_VAL  0xFFE6
#define BT_UUID_CATERPILLAR_TPUT_VAL    0xFFE7
#define BT_UUID_CATERPILLAR_IMUCFG_VAL  0xFFE8
#define BT_UUID_CATERPILLAR_STREAM_VAL  0xFFE9
#define BT_UUID_CATERPILLAR_LOGCTL_VAL  0xFFEA
#define BT_UUID_CATERPILLAR_DUMP_VAL    0xFFEB
#define BT_UUID_CATERPILLAR_MSG_VAL     0xFFEC
#define BT_UUID_CATERPILLAR_LED_VAL     0xFFED
#define BT_UUID_CATERPILLAR_TIME_VAL    0xFFEE
#define BT_UUID_CATERPILLAR_DIR_VAL     0xFFEF
#define BT_UUID_CATERPILLAR_T2LOG_VAL   0xFFF0

#define BT_UUID_CATERPILLAR_SVC  BT_UUID_DECLARE_16(BT_UUID_CATERPILLAR_SVC_VAL)
#define BT_UUID_CATERPILLAR_FREQ BT_UUID_DECLARE_16(BT_UUID_CATERPILLAR_FREQ_VAL)
#define BT_UUID_CATERPILLAR_VOLT BT_UUID_DECLARE_16(BT_UUID_CATERPILLAR_VOLT_VAL)
#define BT_UUID_CATERPILLAR_VDCMEAS \
    BT_UUID_DECLARE_16(BT_UUID_CATERPILLAR_VDCMEAS_VAL)
#define BT_UUID_CATERPILLAR_RAIL BT_UUID_DECLARE_16(BT_UUID_CATERPILLAR_RAIL_VAL)
#define BT_UUID_CATERPILLAR_DRV  BT_UUID_DECLARE_16(BT_UUID_CATERPILLAR_DRV_VAL)
#define BT_UUID_CATERPILLAR_STATUS \
    BT_UUID_DECLARE_16(BT_UUID_CATERPILLAR_STATUS_VAL)
#define BT_UUID_CATERPILLAR_TPUT BT_UUID_DECLARE_16(BT_UUID_CATERPILLAR_TPUT_VAL)
#define BT_UUID_CATERPILLAR_IMUCFG \
    BT_UUID_DECLARE_16(BT_UUID_CATERPILLAR_IMUCFG_VAL)
#define BT_UUID_CATERPILLAR_STREAM \
    BT_UUID_DECLARE_16(BT_UUID_CATERPILLAR_STREAM_VAL)
#define BT_UUID_CATERPILLAR_LOGCTL \
    BT_UUID_DECLARE_16(BT_UUID_CATERPILLAR_LOGCTL_VAL)
#define BT_UUID_CATERPILLAR_DUMP BT_UUID_DECLARE_16(BT_UUID_CATERPILLAR_DUMP_VAL)
#define BT_UUID_CATERPILLAR_MSG  BT_UUID_DECLARE_16(BT_UUID_CATERPILLAR_MSG_VAL)
#define BT_UUID_CATERPILLAR_LED  BT_UUID_DECLARE_16(BT_UUID_CATERPILLAR_LED_VAL)
#define BT_UUID_CATERPILLAR_TIME BT_UUID_DECLARE_16(BT_UUID_CATERPILLAR_TIME_VAL)
#define BT_UUID_CATERPILLAR_DIR  BT_UUID_DECLARE_16(BT_UUID_CATERPILLAR_DIR_VAL)
#define BT_UUID_CATERPILLAR_T2LOG \
    BT_UUID_DECLARE_16(BT_UUID_CATERPILLAR_T2LOG_VAL)

/* GATT service table, defined in ble_interface.c */
extern const struct bt_gatt_service_static caterpillar_svc;

#endif /* BLE_UUIDS_H */
